core/urls.py
from django.urls import path
from core.views import index

app_name = "core"

urlpatterns = [
    path('', index, name='index')
]

encurtador_links/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

forms.py
from django import forms


class UrlForm(forms.Form):
    url = forms.URLField(label='', max_length=100)

core/views.py
from django.shortcuts import render
from forms import UrlForm
from django.contrib import messages
import pyshorteners


def index(request):
    form = UrlForm(request.POST or None)
    url_encurtada = ''
    if str(request.method) == 'POST':
        if form.is_valid():
            link = pyshorteners.Shortener()
            try:
                url_encurtada = link.tinyurl.short(form.cleaned_data["url"])
                messages.success(request, 'URL Gerada Com Sucesso')
            except:
                messages.error(request, 'Não foi possível gerar a URL')
            form = UrlForm()
    context = {
        'form': form,
        'url_encurtada': url_encurtada,
    }
    return render(request, 'index.html', context)

core/templates/index.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Encurtador de Urls</title>

    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Encurtador de links</h1>
        <hr>
        {% bootstrap_messages %}
        <form action="{% url 'core:index' %}" method="post" class="form" autocomplete="off">
           {% csrf_token %}
           {% bootstrap_form form %}
           {% buttons %}
               <button type="submit" class="btn btn-primary">Gerar Nova URL</button>
           {% endbuttons %}
        </form>
        <a href="{{ url_encurtada }}" target="_blank">{{url_encurtada}}</a>
   </div>

    <footer>
        <section class="container flex">
        <div class="item">
            <a href="https://github.com/marcosdaniel0616/encurtador_links" target="_blank">
                <img src="{% static 'images/github.svg' %}" >
            </a>
        </div>
        <div class="item">
            <a href="https://www.linkedin.com/in/marcos-daniel-39bb83193/" target="_blank">
                <img src="{% static 'images/linkedin.svg' %}" >
            </a>
        </div>
        </section>
    </footer>

{% bootstrap_javascript jquery='full' %}
</body>
</html>